app/models/models.py
from flask_sqlalchemy import SQLAlchemy
from app import db
#db = SQLAlchemy()

class Sezioni(db.Model):
    __tablename__ = "sezioni"
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(50), nullable=False)
    video = db.relationship('Video', backref='sezioni', lazy=True)

class Video(db.Model):
    __tablename__ = "video"
    id = db.Column(db.Integer, primary_key=True)
    codice = db.Column(db.String(30), nullable=False)
    sez = db.Column(db.Integer, db.ForeignKey('sezioni.id'),
        nullable=False)
    desc = db.Column(db.String(200))

    def __repr__(self):
        return '<Video %r>' % self.id

app/__init__.py
from flask import Flask
import os
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
import pymysql


app = Flask(__name__)
app.config.from_object(Config)
# app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:rootpass@dbapp:3306/comunidb'

db = SQLAlchemy(app)
db.init_app(app)

login = LoginManager()
login.session_protection = "strong"
login.login_view = 'auth_blueprint.login'
login.init_app(app)

from auth.models import AuthUser
from auth.views import auth_blueprint
app.register_blueprint(auth_blueprint)

app/app.py
from flask import Flask, render_template, request, redirect, render_template_string, session, url_for, flash, g
from datetime import datetime, timedelta 
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_login import current_user, UserMixin,  LoginManager, login_user, logout_user, login_required, fresh_login_required, confirm_login
import pymysql
pymysql.install_as_MySQLdb()
# import MySQLdb
import os
from os.path import join, dirname, realpath


app = Flask(__name__)

login = LoginManager()
login.session_protection = "strong"
login.login_view = 'auth_blueprint.login'
login.init_app(app)

app.config.from_object(Config)
app.config['SQLALCHEMY_DATABASE_URI'] = 'mysql://root:rootpass@'+os.getenv('MYSQL_HOST')+':3306/'+os.getenv('DB_NAME') #dbapp:3306/comunidb'

#MySQLdb.connect(user='root', passwd='rootpass', host="dbapp", port=3306, dbname="comunidb")
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False







db = SQLAlchemy(app)
db.init_app(app)
db.create_all()

from models.models import Sezioni
from auth.models import AuthUser
from auth.views import auth_blueprint
from sez1.views import sez1_bp
from manage_sez.views import sezioni_bp
from manage_video.views import video_bp
app.register_blueprint(auth_blueprint)
app.register_blueprint(sez1_bp)
app.register_blueprint(sezioni_bp)
app.register_blueprint(video_bp)


@app.route("/")
# @fresh_login_required
def view_first_page():
    return render_template("snippets/animazioneLogo.html", sezioni = Sezioni.query.all())

@app.route("/home")

def view_home_page():
    return render_template("home.html", sezioni = Sezioni.query.all())


# @app.route("/second")
# @fresh_login_required
# def view_second_page():
#     return render_template("index.html", title="Second page")

@app.before_request
def before_request():
    #session.permanent = True
    session.modified = True
    app.permanent_session_lifetime = timedelta(minutes=20)
    #g.user = current_user

@login.user_loader
def load_authuser(id):
    return AuthUser.query.get(int(id))

@app.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('view_home_page'))

if __name__ == '__main__':

    app.run(host='0.0.0.0')

app/manage_sez/views.py
from models.models import Sezioni
from flask import Blueprint, render_template, request, redirect
from flask_login import current_user, UserMixin,  LoginManager, login_user, logout_user, login_required, fresh_login_required, confirm_login
from app import db

sezioni_bp = Blueprint('sezioni_bp', __name__,
    template_folder='templates')

@sezioni_bp.route('/sezioni', methods=['GET', 'POST'])
@fresh_login_required
def sezioni():

    if request.method == 'POST':
        try:
            db.session.add(Sezioni(nome=request.form['nome']))
            db.session.commit()
            return redirect('/sezioni')
        except:
            return "There was a problem adding new stuff."
    else:
        
        return render_template('sezioni.html', sezioni = Sezioni.query.all())

@sezioni_bp.route('/delete/<int:id>')
@fresh_login_required
def delete(id):
    sezioni = Sezioni.query.get_or_404(id)

    try:
        db.session.delete(sezioni)
        db.session.commit()
        return redirect('/sezioni')
    except:
        return "There was a problem deleting data."

# @rinnovi_bp.route('/update/<int:id>', methods=['GET', 'POST'])
# @fresh_login_required
# def update(id):
#     rinnovi = Rinnovi.query.get_or_404(id)
#     tecnici = Tecnici.query.all()
#     punti = Punto.query.all()
#     piani = Piani.query.all()

#     if request.method == 'POST':
#         rinnovi.nome = request.form['name']
#         #rinnovi.tec_app = request.form['tec']
#         rinnovi.punto_aff = request.form['aff']
#         #rinnovi.piano = request.form ['piano']

#         try:
#             db.session.commit()
#             return redirect('/')
#         except:
#             return "There was a problem updating data."

#     else:
#         title = "Update Data"
#         return render_template('update.html', title=title, rinnovi=rinnovi, punti=punti)

app/manage_video/views.py
from models.models import Sezioni, Video
from flask import Blueprint, render_template, request, redirect
from flask_login import current_user, UserMixin,  LoginManager, login_user, logout_user, login_required, fresh_login_required, confirm_login
from app import db

video_bp = Blueprint('video_bp', __name__,
    template_folder='templates')

@video_bp.route('/video', methods=['GET', 'POST'])
@fresh_login_required
def video():

    if request.method == 'POST':
        try:
            db.session.add(Video(codice=request.form['codice'], sez=request.form['sez'], desc=request.form['desc']))
            db.session.commit()
            return redirect('/video')
        except:
            return "There was a problem adding new stuff."
    else:
        
        return render_template('video.html', videos = Video.query.all(), sezioni = Sezioni.query.all(), sez=Sezioni)

@video_bp.route('/delete/<int:id>')
@fresh_login_required
def delete(id):
    video = Video.query.get_or_404(id)

    try:
        db.session.delete(video)
        db.session.commit()
        return redirect('/video')
    except:
        return "There was a problem deleting data."

app/sez1/views.py
from flask import Blueprint, render_template, request, redirect
from flask_login import login_required, fresh_login_required
from models.models import Sezioni, Video

sez1_bp = Blueprint('sez1_bp', __name__,
    template_folder='templates')

@sez1_bp.route("/sez/<int:id>")
# @fresh_login_required
def view_home(id):
    
    return render_template("yt_player.html", sezioni = Sezioni.query.all(), videos= Video.query.filter_by(sez=id).all(), \
        last = Video.query.filter_by(sez=id).order_by(Video.id.desc()).first())

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet" href= "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="{{ url_for('static', filename='css/hamburger.css') }}">
    <!-- <link rel="stylesheet" href="{#{{ url_for('static', filename='css/main.css') }}#}"> -->
  
    <script src="https://kit.fontawesome.com/577845f6a5.js" crossorigin="anonymous"></script> 
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.5.4/bootstrap-select.js"></script>
  
  <!-- Optional JavaScript -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script> 
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script> 
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script> 
  
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  
  <!-- (Optional) Latest compiled and minified JavaScript translation files -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/i18n/defaults-*.min.js"></script>
  
  
  <script>
    
  $(function () {
      $('select').selectpicker();
  });
  </script>
        
  
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">




 <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Comune di NomeCittà</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

        {% if current_user.is_anonymous %}
          <li class="nav-item active">
            <a class="nav-link" href="{{ url_for('auth_blueprint.login') }}">Login <span class="sr-only">(current)</span></a>
          </li>
        {% else %}
           

                
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('view_first_page') }}">HOME</a>
                </li>
                {% for sez in sezioni %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('sez1_bp.view_home', id=sez.id) }}">{{ sez.nome }}</a>
                </li>
                {% endfor %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('sezioni_bp.sezioni') }}">Sezioni</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('video_bp.video') }}">Video</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('logout') }}">Logout</a>
                  </li>
           
            {% endif %}
        </ul>
        </div>
        
    </nav> -->

    <!--    Made by Erik Terwan    -->
<!--   24th of November 2015   -->
<!--        MIT License        -->
<nav role="navigation">
    <div id="menuToggle">
      <!--
      A fake / hidden checkbox is used as click reciever,
      so you can use the :checked selector on it.
      -->
      <input type="checkbox" />
      
      <!--
      Some spans to act as a hamburger.
      
      They are acting like a real hamburger,
      not that McDonalds stuff.
      -->
      <span></span>
      <span></span>
      <span></span>
      
      <!--
      Too bad the menu has to be inside of the button
      but hey, it's pure CSS magic.
      -->
      <ul id="menu">
        {% if current_user.is_anonymous %}
          <a href="{{ url_for('auth_blueprint.login') }}"><li>Login</li></a>
        {% else %}  
        <a href="{{ url_for('view_first_page') }}"><li>Home</li></a>
        {% for sez in sezioni %}
          <a href="{{ url_for('sez1_bp.view_home', id=sez.id) }}"><li>{{ sez.nome }}</li></a>
        {% endfor %}
        <a href="{{ url_for('sezioni_bp.sezioni') }}"><li>Sezioni</li></a>
        <a href="{{ url_for('video_bp.video') }}"><li>Video</li></a>
        <a href="{{ url_for('logout') }}" target="_blank"><li>Logout</li></a>
        {% endif %}
      </ul>
    </div>
  </nav>
  <br>
  <br>



{% block content %}

{% endblock %}


</html>

app/templates/base3.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width"/>
    <meta http-equiv="X-UA-Compatible" content="ie-edge"/>

	 <meta name="keywords" content="app, seo, web positioning"/>
  	<meta name="author" content="Carmelo Marasco"/>
  	<title>QuivideoTV</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css"/>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base3.css') }}">
    <link href="https://fonts.googleapis.com/css?family=Yantramanav:300,400,500,700&amp;display=swap" rel="stylesheet"/>
  </head>
  
  
  <!-- Navigation -->
  <body class="body">
    <header class="header" >
      <nav class="navbar">
        <input type="checkbox" id="check"/>
        <label for="check" class="check-btn"><i class="check-btn__i fas fa-bars"></i></label>
        <label class="brand"><a class="brand__link" href="#">QuivideoTV</a></label>
        <div class="nav-wrapper">
          <ul class="menu">
            
            <li class="menu__item"><a class="menu__link" href="{{ url_for('view_home_page') }}">Home</a></li>
            <li class="menu__item"><a class="menu__link" href="#">CHI SIAMO</a></li>
            <li class="menu__item"><a class="menu__link" href="#">CONTATTI</a></li>
            <li class="menu__item"><a class="menu__link" href="{{ url_for('auth_blueprint.login') }}">Area Riservata</a></li>
            {% if not current_user.is_anonymous %}  
            <li class="menu__item"><a class="menu__link" href="{{ url_for('sezioni_bp.sezioni') }}">Sezioni</a></li>
            <li class="menu__item"><a class="menu__link" href="{{ url_for('video_bp.video') }}"> Video</a></li>
              <li class="menu__item"><a class="menu__link" href="{{ url_for('logout') }}"> Logout</a></li>
            
            {% endif %}
          </ul>
        </div>
      </nav>
    </header>
    
    

      
    {% block content %}

    {% endblock %}
  

  
    
    <footer class="footer">
      <div class="icons-social">
        <ul class="list-social">
          <li class="icons-social__item"><a class="icons-social__link" href="#"><i class="icons-social__i fab fa-codepen"></i></a></li>              
          <li class="icons-social__item"><a class="icons-social__link" href="#"><i class="icons-social__i fab fa-instagram"></i></a></li>
          <li class="icons-social__item"><a class="icons-social__link" href="#"><i class="icons-social__i fab fa-facebook"></i></a></li>
          <li class="icons-social__item"><a class="icons-social__link" href="#"><i class="icons-social__i fab fa-twitter"></i></a></li>
          <li class="icons-social__item"><a class="icons-social__link" href="#"><i class="icons-social__i fab fa-linkedin"></i></a></li>
        </ul>
      </div>
      <div class="container-footer"> 
        <p>Sviluppata da <a class="container-footer__link" href="https://codepen.io/Yulian_b/" target="_blank">Hirundinidae Società Cooperativa</a> | Copyright &copy; 2020</p>
      </div>
    </footer>
  </body>
</html>

app/templates/home.html
{% extends 'base3.html' %} 

{% block content %}

<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>QuivideoTV</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="css/main.css" />
    <script type="text/javascript" src="js/main.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home_style.css') }}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz"
        crossorigin="anonymous">
</head>


<!-- Start Site -->

<body>
    <!-- Navigation -->
    <!-- <header>
        <div class="header-grid">
            <div class="header-logo">
                <img src="https://i.ibb.co/8YSbYjm/logo-2x.png" alt="Image of the logo for the website">
            </div>
            <nav class="main-nav">
                <ul>
                    <li>
                        <a target="_blank" href="#">Resume</a>
                    </li>
                    <li>
                        <a href="#">Connect</a>
                    </li>
                </ul>
            </nav>
        </div>
    </header> -->
    <main>

        <!-- Hero Section -->
        <section class="hero-section">
            <div class="hero-grid">

                <div class="hero-content">
                    <p class="hero-title">Comune di ......</p>
                    <div class=social-media>
                        <a target="_blank" href="#">
                            <i class="fab fa-github-alt"></i>
                        </a>
                        <a target="_blank" href="#">
                            <i class="fab fa-linkedin-in"></i>
                        </a>
                        <a target="_blank" href="#">
                            <i class="fab fa-dribbble"></i>
                        </a>
                        <a href="mailto:mail@gmail.com">
                            <i class="far fa-envelope"></i>
                        </a>
                    </div>
                </div>
            </div>
        </section>
        <!-- Work Section -->
        <section class="work-section">
            <div class="section-title">
  
            </div>
            <div class="work-grid">
                
                <div class="card-1 work-card" onclick="projectOne()">
                    <h6 class="card-subhead">Video</h6>
                    <p class="card-header">Consigli Comunali</p>
                </div>
                
                <div class="card-2 work-card" onclick="projectTwo()">
                    <h6 class="card-subhead">Video</h6>
                    <p class="card-header">Sezione 2</p>
                </div>
                <div class="card-3 work-card" onclick="projectThree()">
                    <h6 class="card-subhead">Video</h6>
                    <p class="card-header">Eventi</p>
                </div>
            </div>
        </section>
        <!-- Footer -->
        <!-- <footer>
            <p>© COPYRIGHT 2020 Hirundinidae Società Cooperativa <span style="color: #e25555;">&#9829;</span></p>
        </footer> -->
    </main>
</body>

<script>

$(document).ready(function () {
    // Open in new window
        $('.click').each(function() {
        var link = $(this).html();
        $(this).contents().wrap('<a href="google.com"></a>');
        });
});

// Make Card One Clickable
function projectOne() {
    window.open("{{ url_for('sez1_bp.view_home', id=1) }}");
}

// Make Card Two Clickable
function projectTwo() {
    window.open("{{ url_for('sez1_bp.view_home', id=3) }}");
}

// Make Card Three Clickable
function projectThree() {
    window.open("https://github.com/alexdavidjohnson/Front-End-Portfolio-Project");
}
</script>

</html>

{% endblock content %}

app/templates/home_old.html
{% extends 'base.html' %} 

{% block content %}
{% include 'snippets/sky.html' %}

{% endblock content %}

app/templates/homesky.html
<head>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/sky.css') }}">
</head>

<div id="root" />
<script src="https://cdn.jsdelivr.net/npm/animejs@3.0.1/lib/anime.min.js"></script>

<script>
    // Twinkling Night Sky by Sharna

class StarrySky extends React.Component {
  state = {
    num: 60,
    vw: Math.max(document.documentElement.clientWidth, window.innerWidth || 0),
    vh: Math.max(document.documentElement.clientHeight, window.innerHeight || 0)
  };
  starryNight = () => {
    anime({
      targets: ["#sky .star"],
      opacity: [
        {
          duration: 700,
          value: "0"
        },
        {
          duration: 700,
          value: "1"
        }
      ],
      easing: "linear",
      loop: true,
      delay: (el, i) => 50 * i
    });
  };
  shootingStars = () => {
    anime({
      targets: ["#shootingstars .wish"],
      easing: "linear",
      loop: true,
      delay: (el, i) => 1000 * i,
      opacity: [
        {
          duration: 700,
          value: "1"
        }
      ],
      width: [
        {
          value: "150px"
        },
        {
          value: "0px"
        }
      ],
      translateX: 350
    });
  };
  randomRadius = () => {
    return Math.random() * 0.7 + 0.6;
  };
  getRandomX = () => {
    return Math.floor(Math.random() * Math.floor(this.state.vw)).toString();
  };
  getRandomY = () => {
    return Math.floor(Math.random() * Math.floor(this.state.vh)).toString();
  };
  componentDidMount() {
    this.starryNight();
    this.shootingStars();
  }
  render() {
    const { num } = this.state;
    return (
      <div id="App">
        <svg id="sky">
          {[...Array(num)].map((x, y) => (
            <circle
              cx={this.getRandomX()}
              cy={this.getRandomY()}
              r={this.randomRadius()}
              stroke="none"
              strokeWidth="0"
              fill="white"
              key={y}
              className="star"
            />
          ))}
        </svg>
        <div id="shootingstars">
          {[...Array(60)].map((x, y) => (
            <div
              key={y}
              className="wish"
              style={{
                left: `${this.getRandomY()}px`,
                top: `${this.getRandomX()}px`
              }}
            />
          ))}
        </div>
      </div>
    );
  }
}

ReactDOM.render(<StarrySky />, document.getElementById("root"));

</script>

app/templates/index.html
{% extends 'base3.html' %} 

{% block content %}
<!-- see http://www.woosterwebdesign.com/responsive-youtube-player-with-playlist/ -->

  <head>
  	<meta name="viewport" content="width=device-width, maximum-scale=1, user-scalable=no, target-densitydpi=device-dpi">
  	<title>Demo: videoplayer comuni</title> 
  	<!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" /> -->

	  

	  <!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script> -->
	  <!-- <script src="https://cdn.jsdelivr.net/gh/BMSVieira/BVAmbient@413fec0/js/bvambient.js"></script> -->
	  <link rel="stylesheet" href="{{ url_for('static', filename='css/player.css') }}">


  </head>
  <body>
	  <!-- <div class="title"><h2>Demo: videoplayer comuni </h2></div> -->
	  <div>
    <section class="hero-section"  >
		
		<!-- <div id="ambient" style="overflow:hidden; position: absolute; width:100%; height: 100%;"></div> -->
  	<div class="vid-main-wrapper" >
		
  		<!-- THE YOUTUBE PLAYER -->
  		<div class="vid-container" > 
			  
		    <iframe id="vid_frame" src="https://www.youtube.com/embed/{{ last.codice }}?rel=0&showinfo=0&autohide=1" frameborder="0" width="560" height="315"></iframe>
		</div>

		<!-- THE PLAYLIST -->
		<div class="vid-list-container" style = "background: #222" >
			<ol id="vid-list">

				{% for video in videos %}
				<li>
					<a href="javascript:void();" onClick="document.getElementById('vid_frame').src='https://youtube.com/embed/{{ video.codice }}?autoplay=1&rel=0&showinfo=0&autohide=1'">
					  <span class="vid-thumb"><img width=72 src="https://img.youtube.com/vi/{{ video.codice }}/default.jpg" /></span>
					  <div class="desc">{{ video.desc}}</div>
					</a>
				  </li>


				  <!-- <div class="vid-list">
				
					<div class="vid-item" onClick="document.getElementById('vid_frame').src='http://www.youtube.com/embed/{{ video.codice }}?rel=0&showinfo=0&autohide=1'" >
					  <div class="thumb"><img width=72 src="http://img.youtube.com/vi/{{ video.codice }}/0.jpg"></div>
					  <div class="desc">{{ video.desc}} </div>
					</div>
					
   
			   
				</div> -->

				  {% endfor %}


			</ol>


        </div>

        <!-- LEFT AND RIGHT ARROWS -->
        <!-- <div class="arrows">
        	<div class="arrow-left"><i class="fa fa-chevron-left fa-lg"></i></div>
        	<div class="arrow-right"><i class="fa fa-chevron-right fa-lg"></i></div>
        </div>
	  </div> -->
	  
	  <!-- <script src="https://cpwebassets.codepen.io/assets/common/stopExecutionOnTimeout-157cd5b220a5c80d4ff8e0e70ac069bffd87a61252088146915e8726e5d9f147.js"></script> -->
	  <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> -->
  	<!-- JS FOR SCROLLING THE ROW OF THUMBNAILS -->
	  </div>
	
	</section>  
</div>
  </body>
	  <script type="text/javascript">
  		// $(document).ready(function () {
		//     $(".arrow-right").bind("click", function (event) {
		//         event.preventDefault();
		//         $(".vid-list-container").stop().animate({
		//             scrollup: "+=336"
		//         }, 750);
		//     });
		//     $(".arrow-left").bind("click", function (event) {
		//         event.preventDefault();
		//         $(".vid-list-container").stop().animate({
		//             scrollLeft: "-=336"
		//         }, 750);
		//     });
		// });
		$(document).ready(function () {
  $('.vid-item').each(function(index){
    $(this).on('click', function(){
      var current_index = index+1;
      $('.vid-item .thumb').removeClass('active');
      $('.vid-item:nth-child('+current_index+') .thumb').addClass('active');
    });
  });
});
  	</script>


  	<!-- google analytics -->
  	<script type="text/javascript">

		/* Check External Source: bvambient.js */ 
	// 	document.addEventListener("DOMContentLoaded", function() {
	// 					var demo1 = new BVAmbient({
	// 				selector: "#ambient",
	// 				fps: 60,
	// 				max_transition_speed: 12000,
	// 				min_transition_speed: 8000,
	// 				particle_number: 30,
	// 				particle_maxwidth: 60,
	// 				particle_minwidth: 10,
	// 				particle_radius: 50,
	// 				particle_opacity: true,
	// 				particle_colision_change: true,
	// 				particle_background: "#58c70c",
	// 				particle_image: {
	// 				image: false,
	// 				src: ""
	// 				},
	// 				responsive: [
	// 					{
	// 					breakpoint: 768,
	// 					settings: {
	// 						particle_number: "15"
	// 					}
	// 					},
	// 					{
	// 					breakpoint: 480,
	// 					settings: {
	// 						particle_number: "10"
	// 					}
	// 					}
	// 				]
	// 			});
	// 		});

	// </script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/js/all.min.js" integrity="sha256-qM7QTJSlvtPSxVRjVWNM2OfTAz/3k5ovHOKmKXuYMO4=" crossorigin="anonymous"></script>



{% endblock content %}

app/templates/prova.html
{% extends 'base3.html' %} 

{% block content %}
<html>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home_style.css') }}">
    <body>
        <main>
            <section class="hero-section">
                <p>Ciao</p>
            </section>
        </main>
    </body>
</html>

{% endblock content %}

app/templates/snippets/sezform.html
<form class="row form-inline mb-3" action="/sezioni" method="POST" enctype="multipart/form-data">

    <div class="col-sm mt-2  form-group" >

    

    <label class="col-sm-1 mt-2" for="mensilita" >Quota:</label>
      <input class="form-control col-sm-2 mt-2" type="text" id="mensiita" name="nome" placeholder="Inserisci nome sezione">
      <div class="col-sm-2 mt-2">
      <button  type="submit" class="btn btn-primary">Add</button>
    </div>
  

  <!-- <div calss="my-2">
    <button type="submit" class="btn btn-primary mx-4">Add</button>
  </div>
  <input type="number" step="any" name="mensilita" min="0"/>

</div> -->
  </div>
  </form>